### PR TITLE
Use syberia_create to create the initial syberia repo

### PR DESCRIPTION
**Pull request by peterhurford**

### CODE REVIEW

**Comment by robertzk** [comment]
Not bad, but this is way too much. The final creation will be a simple [outline](https://github.com/syberia/engines.sy) with a bunch of readmes, not the entirety of the modeling engine...

**Comment by robertzk** [comment]
Hold off on this.

**Comment by robertzk** [comment]
Syberia does not currently support Windows. The timeline for that is the 1.0 release in late 2016.

**Comment by robertzk** [comment]
This needs to wait on https://github.com/robertzk/syberia/pull/83

**Comment by peterhurford** [comment]
Waiting. :)

**Pull request closed without merging**
